import React, { useState } from 'react';
import { 
  Search, 
  Sparkles, 
  ExternalLink, 
  Github, 
  Terminal, 
  BookOpen, 
  Layers, 
  Briefcase, 
  GraduationCap, 
  Share2, 
  Download, 
  FileText, 
  CheckCircle2, 
  AlertCircle,
  HelpCircle,
  Clock,
  Compass,
  Zap,
  Code
} from 'lucide-react';
import { PRESET_PAPERS, AnalysisResult, TokenMetrics, StudentProject } from './data/samplePapers';
import { MermaidViewer } from './components/MermaidViewer';
import { CoreConceptView } from './components/CoreConceptView';
import { StudentProjectsView } from './components/StudentProjectsView';
import { TokenBudgetGauge } from './components/TokenBudgetGauge';
import { RawOutputViewer } from './components/RawOutputViewer';
import { AdvisorChatModal } from './components/AdvisorChatModal';

export default function App() {
  const [selectedPresetId, setSelectedPresetId] = useState<string>('mamba');
  const [paperUrlInput, setPaperUrlInput] = useState<string>('');
  const [isAnalyzing, setIsAnalyzing] = useState<boolean>(false);
  const [analysisError, setAnalysisError] = useState<string | null>(null);

  // Initialize with Mamba paper preset
  const defaultPaper = PRESET_PAPERS[0];
  const [currentAnalysis, setCurrentAnalysis] = useState<AnalysisResult>(defaultPaper.data);
  const [tokenMetrics, setTokenMetrics] = useState<TokenMetrics>(defaultPaper.tokenMetrics);

  // View state
  const [activeTab, setActiveTab] = useState<'all' | 'concept' | 'flowchart' | 'projects' | 'raw'>('all');
  const [isAdvisorOpen, setIsAdvisorOpen] = useState<boolean>(false);
  const [advisorProject, setAdvisorProject] = useState<StudentProject | null>(null);

  // Handle Preset selection
  const handleSelectPreset = (preset: typeof PRESET_PAPERS[0]) => {
    setSelectedPresetId(preset.id);
    setPaperUrlInput(preset.url);
    setCurrentAnalysis(preset.data);
    setTokenMetrics(preset.tokenMetrics);
    setAnalysisError(null);
  };

  // Submit Paper URL for dynamic analysis
  const handleAnalyzePaper = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    const query = paperUrlInput.trim();
    if (!query) return;

    // Check if it matches a preset first for instant switch
    const match = PRESET_PAPERS.find(
      p => p.url.toLowerCase() === query.toLowerCase() || 
           p.arxivId === query || 
           p.title.toLowerCase().includes(query.toLowerCase())
    );
    if (match) {
      handleSelectPreset(match);
      return;
    }

    setIsAnalyzing(true);
    setAnalysisError(null);

    try {
      const response = await fetch('/api/analyze-paper', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: query, title: query }),
      });

      const result = await response.json();
      if (!response.ok || !result.success) {
        throw new Error(result.error || 'Failed to analyze paper. Please check the URL or try an arXiv paper link.');
      }

      setCurrentAnalysis(result.data);
      if (result.tokenMetrics) {
        setTokenMetrics(result.tokenMetrics);
      }
      setSelectedPresetId('custom');
    } catch (err: any) {
      console.error('Analysis error:', err);
      setAnalysisError(err.message || 'An error occurred during paper parsing.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  const openAdvisorForProject = (project: StudentProject) => {
    setAdvisorProject(project);
    setIsAdvisorOpen(true);
  };

  const handleExportBrief = () => {
    const brief = `# Research Agent Brief: ${currentAnalysis.paperMetadata.title}
Authors: ${currentAnalysis.paperMetadata.authors.join(', ')}
Venue/arXiv: ${currentAnalysis.paperMetadata.venueOrArxiv}

## 1. CORE CONCEPT EXTRACTION (< 300 words)
### Problem Statement:
${currentAnalysis.coreConcept.problemStatement}

### Primary Methodology:
${currentAnalysis.coreConcept.primaryMethodology}

### Mathematical/Algorithmic Breakthroughs:
${currentAnalysis.coreConcept.mathematicalAlgorithmicBreakthroughs}

### Accessible Summary:
${currentAnalysis.coreConcept.accessibleSummary}

## 2. ARCHITECTURAL FLOWCHART (Mermaid.js)
[FLOWCHART]
\`\`\`mermaid
${currentAnalysis.flowchart.mermaidCode}
\`\`\`

## 3. FUTURE WORK & INTERNSHIP OPPORTUNITIES (3rd-Year CS Student)
${currentAnalysis.studentProjects.map((p, i) => `
### Project ${i + 1}: ${p.title}
- **Exact Extension:** ${p.exactExtension}
- **Targeted Performance Metric:** ${p.targetedPerformanceMetric}
- **Recommended Tech Stack:** ${Array.isArray(p.recommendedTechStack) ? p.recommendedTechStack.join(', ') : p.recommendedTechStack}
- **Resume Bullet:** • ${p.resumeBulletPoint}
`).join('\n')}

---
Generated by CS Research Agent (Token Budget Constrained < 25,000 tokens)
`;

    const blob = new Blob([brief], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${currentAnalysis.paperMetadata.title.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()}_research_brief.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans selection:bg-indigo-500 selection:text-white">
      {/* Top Navbar */}
      <header className="sticky top-0 z-40 bg-slate-950/90 backdrop-blur-md border-b border-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-indigo-600 to-cyan-500 p-0.5 shadow-md shadow-indigo-500/20">
              <div className="w-full h-full bg-slate-950 rounded-[10px] flex items-center justify-center">
                <Compass className="w-5 h-5 text-indigo-400" />
              </div>
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-sm font-bold tracking-tight text-slate-100 sm:text-base">
                  CS Research Agent
                </h1>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-indigo-500/10 text-indigo-300 border border-indigo-500/20 hidden sm:inline">
                  Paper Parser & Architecture Architect
                </span>
              </div>
              <p className="text-[11px] text-slate-400 font-mono hidden md:block">
                Token-Efficient Academic Analysis • Mermaid.js Flowcharts • Resume Projects
              </p>
            </div>
          </div>

          {/* Quick Actions */}
          <div className="flex items-center space-x-2">
            <button
              onClick={() => {
                setAdvisorProject(null);
                setIsAdvisorOpen(true);
              }}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-200 hover:text-white bg-slate-900 hover:bg-slate-800 border border-slate-800 rounded-lg transition-colors"
            >
              <GraduationCap className="w-3.5 h-3.5 text-indigo-400" />
              <span className="hidden sm:inline">Student Research Advisor</span>
              <span className="sm:hidden">Advisor</span>
            </button>
            <button
              onClick={handleExportBrief}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-white bg-indigo-600 hover:bg-indigo-500 rounded-lg shadow-sm transition-colors"
              title="Download Complete Research Brief"
            >
              <Download className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Export Brief (.md)</span>
            </button>
          </div>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">
        {/* Research Paper Input Section */}
        <section className="bg-slate-900/90 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl">
          <form onSubmit={handleAnalyzePaper} className="space-y-3">
            <div className="flex flex-col sm:flex-row gap-2">
              <div className="relative flex-1">
                <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  value={paperUrlInput}
                  onChange={(e) => setPaperUrlInput(e.target.value)}
                  placeholder="Paste research paper URL (e.g. arXiv link: https://arxiv.org/abs/2312.00752, OpenReview, or paper title)..."
                  className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-10 pr-4 py-2.5 text-xs sm:text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 font-sans"
                />
              </div>
              <button
                type="submit"
                disabled={isAnalyzing}
                className="flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-400 text-white text-xs sm:text-sm font-medium transition-all shadow-md shadow-indigo-600/20 disabled:opacity-50"
              >
                {isAnalyzing ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    <span>Parsing Paper...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 text-amber-300" />
                    <span>Parse Paper & Architecture</span>
                  </>
                )}
              </button>
            </div>

            {/* Landmark Papers Fast Presets */}
            <div className="flex flex-wrap items-center gap-2 pt-1">
              <span className="text-[11px] font-mono text-slate-400 flex items-center gap-1">
                <Zap className="w-3 h-3 text-amber-400" />
                Landmark Papers:
              </span>
              {PRESET_PAPERS.map((preset) => (
                <button
                  key={preset.id}
                  type="button"
                  onClick={() => handleSelectPreset(preset)}
                  className={`text-xs px-2.5 py-1 rounded-lg border font-mono transition-all ${
                    selectedPresetId === preset.id
                      ? 'bg-indigo-600/20 border-indigo-500/50 text-indigo-300'
                      : 'bg-slate-950/70 border-slate-800 text-slate-400 hover:text-slate-200 hover:border-slate-700'
                  }`}
                >
                  {preset.title.split(':')[0]}
                </button>
              ))}
            </div>
          </form>

          {analysisError && (
            <div className="mt-3 p-3 rounded-lg bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs flex items-center gap-2">
              <AlertCircle className="w-4 h-4 flex-shrink-0" />
              <span>{analysisError}</span>
            </div>
          )}
        </section>

        {/* Paper Overview Header + Token Gauge */}
        <section className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          {/* Paper Metadata Card */}
          <div className="lg:col-span-2 bg-slate-900/90 border border-slate-800 rounded-xl p-4 sm:p-5 flex flex-col justify-between">
            <div>
              <div className="flex flex-wrap items-center gap-2 mb-2">
                <span className="text-[11px] font-mono font-semibold px-2 py-0.5 rounded bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                  {currentAnalysis.paperMetadata.venueOrArxiv || 'Research Publication'}
                </span>
                <span className="text-[11px] font-mono text-slate-400">
                  Year: {currentAnalysis.paperMetadata.year}
                </span>
                {currentAnalysis.paperMetadata.tags && (
                  <div className="flex items-center gap-1.5 flex-wrap">
                    {currentAnalysis.paperMetadata.tags.slice(0, 3).map((tag, tIdx) => (
                      <span key={tIdx} className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-slate-800 text-slate-300">
                        #{tag}
                      </span>
                    ))}
                  </div>
                )}
              </div>

              <h2 className="text-lg sm:text-xl font-bold text-slate-100 font-serif leading-snug">
                {currentAnalysis.paperMetadata.title}
              </h2>

              <p className="text-xs text-slate-400 mt-2 font-mono">
                Authors: {currentAnalysis.paperMetadata.authors.join(', ')}
              </p>
            </div>

            <div className="mt-4 pt-3 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-3 text-xs">
              <div className="flex items-center gap-3">
                {currentAnalysis.paperMetadata.githubUrl ? (
                  <a
                    href={currentAnalysis.paperMetadata.githubUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center gap-1.5 text-slate-300 hover:text-white font-mono"
                  >
                    <Github className="w-3.5 h-3.5" />
                    <span>Open Source Implementation</span>
                  </a>
                ) : (
                  <span className="text-slate-400 font-mono text-[11px]">
                    Implementation available in research community
                  </span>
                )}
              </div>
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-mono text-emerald-400 flex items-center gap-1">
                  <CheckCircle2 className="w-3 h-3" />
                  CS Agent Ingestion Complete
                </span>
              </div>
            </div>
          </div>

          {/* Operational Constraint: Token Efficiency Gauge */}
          <div className="lg:col-span-1">
            <TokenBudgetGauge metrics={tokenMetrics} />
          </div>
        </section>

        {/* Navigation Tabs */}
        <div className="flex items-center gap-2 border-b border-slate-800 pb-2 overflow-x-auto no-scrollbar">
          <button
            onClick={() => setActiveTab('all')}
            className={`px-3 py-1.5 text-xs rounded-lg font-medium transition-all ${
              activeTab === 'all'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
            }`}
          >
            All 3 Steps Overview
          </button>
          <button
            onClick={() => setActiveTab('concept')}
            className={`px-3 py-1.5 text-xs rounded-lg font-medium transition-all flex items-center gap-1.5 ${
              activeTab === 'concept'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
            }`}
          >
            <BookOpen className="w-3.5 h-3.5" />
            <span>1. Core Concept (&lt;300w)</span>
          </button>
          <button
            onClick={() => setActiveTab('flowchart')}
            className={`px-3 py-1.5 text-xs rounded-lg font-medium transition-all flex items-center gap-1.5 ${
              activeTab === 'flowchart'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>2. Architecture Flowchart</span>
          </button>
          <button
            onClick={() => setActiveTab('projects')}
            className={`px-3 py-1.5 text-xs rounded-lg font-medium transition-all flex items-center gap-1.5 ${
              activeTab === 'projects'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
            }`}
          >
            <Briefcase className="w-3.5 h-3.5" />
            <span>3. Resume Project Extensions</span>
          </button>
          <button
            onClick={() => setActiveTab('raw')}
            className={`px-3 py-1.5 text-xs rounded-lg font-medium transition-all flex items-center gap-1.5 ${
              activeTab === 'raw'
                ? 'bg-indigo-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
            }`}
          >
            <Terminal className="w-3.5 h-3.5" />
            <span>Raw Agent Output</span>
          </button>
        </div>

        {/* Tab 1: All View (Standard Workflow) */}
        {(activeTab === 'all' || activeTab === 'concept') && (
          <section id="step-1">
            <CoreConceptView 
              concept={currentAnalysis.coreConcept} 
              paperTitle={currentAnalysis.paperMetadata.title}
            />
          </section>
        )}

        {(activeTab === 'all' || activeTab === 'flowchart') && (
          <section id="step-2" className="space-y-2">
            <div className="flex items-center justify-between px-1">
              <h3 className="text-sm font-semibold text-slate-200 flex items-center gap-2">
                <span>2. Architectural Flowchart (Mermaid.js graph TD)</span>
              </h3>
            </div>
            <MermaidViewer
              chart={currentAnalysis.flowchart.mermaidCode}
              nodeExplanations={currentAnalysis.flowchart.nodeExplanations}
              paperTitle={currentAnalysis.paperMetadata.title}
            />
          </section>
        )}

        {(activeTab === 'all' || activeTab === 'projects') && (
          <section id="step-3">
            <StudentProjectsView
              projects={currentAnalysis.studentProjects}
              paperTitle={currentAnalysis.paperMetadata.title}
              onAskAboutProject={openAdvisorForProject}
            />
          </section>
        )}

        {/* Tab: Raw Agent Output View */}
        {activeTab === 'raw' && (
          <section>
            <RawOutputViewer
              rawOutput={currentAnalysis.rawAgentOutput}
              paperTitle={currentAnalysis.paperMetadata.title}
            />
          </section>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-900 bg-slate-950 py-6 mt-12 text-slate-400 text-xs">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center space-x-2">
            <span className="font-mono text-slate-400">CS Research Agent</span>
            <span>•</span>
            <span>Operational Constraints: Token Budget &lt; 25k, Core Concept &lt; 300 words</span>
          </div>
          <div className="flex items-center space-x-4 font-mono text-[11px]">
            <span>Mermaid.js graph TD</span>
            <span>PyTorch & ONNX Extensions</span>
          </div>
        </div>
      </footer>

      {/* CS Student Research Advisor Modal */}
      <AdvisorChatModal
        isOpen={isAdvisorOpen}
        onClose={() => setIsAdvisorOpen(false)}
        paperTitle={currentAnalysis.paperMetadata.title}
        paperSummary={currentAnalysis.coreConcept.accessibleSummary}
        selectedProject={advisorProject}
      />
    </div>
  );
}
